import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Navbar from '@/components/Navbar'
import Featured from '@/components/Featured'
import MoviesSection from '@/components/MoviesSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/netflixicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <Featured/>
        <MoviesSection/>
      </main>
    </>
  )
}
